export const users = [
  {
    _id: '63d36c1c1ded5b3c9730811a',
    index: 0,
    guid: '83195bb7-18a2-4bc2-8813-a17485a7b5f8',
    isActive: true,
    balance: '$2,007.89',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'blue',
    name: 'Clark Cross',
    gender: 'male',
    company: 'GEEKMOSIS',
    email: 'clarkcross@geekmosis.com',
    phone: '+1 (979) 401-2032',
    address: '180 Beadel Street, Boling, Maryland, 3086',
    about:
      'Ut consectetur pariatur irure ipsum qui. Cillum in velit ullamco amet id irure Lorem ad labore culpa labore proident officia sunt. Ullamco quis cupidatat laboris duis non aliqua mollit nisi mollit est ex id. Sint ea nulla nulla nulla eiusmod dolore id Lorem elit reprehenderit ad. Dolore enim ipsum tempor ullamco non quis consequat. Eiusmod reprehenderit qui eu aute. Consectetur nisi dolor mollit ut excepteur ullamco incididunt adipisicing minim quis.\r\n',
    registered: '2020-10-29T05:49:20 -09:00',
    latitude: -10.135867,
    longitude: -50.514669,
    tags: ['incididunt', 'dolor', 'est', 'anim', 'non', 'ea', 'est'],
    friends: [
      {
        id: 0,
        name: 'Allison Valentine',
      },
      {
        id: 1,
        name: 'Gibson Lopez',
      },
      {
        id: 2,
        name: 'Billie Floyd',
      },
    ],
    greeting: 'Hello, Clark Cross! You have 1 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '63d36c1c0d6b4531753471f8',
    index: 1,
    guid: '5be7101f-75d2-43ac-b73f-60ccd453e5a0',
    isActive: false,
    balance: '$1,027.28',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'green',
    name: 'Bryan Hart',
    gender: 'male',
    company: 'SURETECH',
    email: 'bryanhart@suretech.com',
    phone: '+1 (912) 533-2398',
    address: '327 Jamaica Avenue, Henrietta, New Mexico, 273',
    about:
      'Dolore sunt sit voluptate dolor sit non dolore esse voluptate est. Enim Lorem non consequat veniam. Ex minim non eu quis exercitation id reprehenderit ad ipsum deserunt est deserunt in officia. Veniam ad exercitation dolore irure ipsum id. Veniam laboris eu Lorem ex anim velit velit enim. Esse in ex incididunt culpa nisi proident mollit irure minim magna. Aliquip mollit elit nisi anim eu Lorem est adipisicing magna pariatur.\r\n',
    registered: '2017-10-26T03:06:02 -09:00',
    latitude: 66.516176,
    longitude: -104.783243,
    tags: [
      'minim',
      'cupidatat',
      'est',
      'est',
      'eiusmod',
      'incididunt',
      'eiusmod',
    ],
    friends: [
      {
        id: 0,
        name: 'Wiggins Moses',
      },
      {
        id: 1,
        name: 'Deirdre Dudley',
      },
      {
        id: 2,
        name: 'Erin Beck',
      },
    ],
    greeting: 'Hello, Bryan Hart! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '63d36c1c5de4b293692014be',
    index: 2,
    guid: 'a073289b-edfe-440c-815f-3841baedb6c0',
    isActive: true,
    balance: '$3,879.87',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'brown',
    name: 'Shanna Vaughan',
    gender: 'female',
    company: 'FANFARE',
    email: 'shannavaughan@fanfare.com',
    phone: '+1 (828) 469-2798',
    address: '231 Nassau Avenue, Greenbush, Michigan, 7000',
    about:
      'Lorem ad sunt mollit dolor commodo amet labore deserunt velit dolore tempor. Labore consectetur proident excepteur incididunt cillum laboris aliquip aliqua sunt dolore culpa voluptate voluptate elit. Ullamco veniam do cupidatat eiusmod commodo dolore consectetur magna consequat enim voluptate. Ex qui cupidatat ut sunt dolore sunt mollit nostrud fugiat tempor id eiusmod. Do consequat amet deserunt sunt adipisicing esse. Aute nostrud duis id minim laboris commodo.\r\n',
    registered: '2018-07-19T01:37:55 -09:00',
    latitude: -36.440816,
    longitude: -0.046276,
    tags: ['magna', 'cupidatat', 'sunt', 'ea', 'culpa', 'eu', 'officia'],
    friends: [
      {
        id: 0,
        name: 'Antonia Jordan',
      },
      {
        id: 1,
        name: 'Jacqueline Meyers',
      },
      {
        id: 2,
        name: 'Petra Estrada',
      },
    ],
    greeting: 'Hello, Shanna Vaughan! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '63d36c1c48963070fc615933',
    index: 3,
    guid: 'a1f97227-99a6-4d5d-af23-bc1a5ad20580',
    isActive: true,
    balance: '$2,108.07',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'green',
    name: 'Gordon Powell',
    gender: 'male',
    company: 'COMTRACT',
    email: 'gordonpowell@comtract.com',
    phone: '+1 (976) 506-2458',
    address: '646 Irwin Street, Salvo, Guam, 9132',
    about:
      'Aliqua tempor laboris esse irure do officia nostrud adipisicing velit est ea exercitation in. Sit aliqua aute consequat consectetur exercitation eiusmod Lorem exercitation elit tempor aliquip excepteur ex minim. Ea sit aliquip eiusmod deserunt. Culpa veniam cupidatat exercitation nostrud qui nisi. In duis veniam labore sit id duis et eu deserunt. Excepteur labore do aliqua deserunt proident cillum laborum nulla cupidatat.\r\n',
    registered: '2017-11-28T08:36:23 -09:00',
    latitude: -81.393687,
    longitude: -108.740603,
    tags: [
      'voluptate',
      'sit',
      'minim',
      'elit',
      'aliquip',
      'dolore',
      'cupidatat',
    ],
    friends: [
      {
        id: 0,
        name: 'Cara Compton',
      },
      {
        id: 1,
        name: 'Armstrong Howe',
      },
      {
        id: 2,
        name: 'Maria Waters',
      },
    ],
    greeting: 'Hello, Gordon Powell! You have 3 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '63d36c1ca79faa3f68c781b1',
    index: 4,
    guid: 'f23eaf6d-d6e8-48e9-b1f8-2b09b3b013af',
    isActive: false,
    balance: '$1,931.70',
    picture: 'http://placehold.it/32x32',
    age: 21,
    eyeColor: 'blue',
    name: 'Maryellen Foley',
    gender: 'female',
    company: 'ERSUM',
    email: 'maryellenfoley@ersum.com',
    phone: '+1 (992) 514-3981',
    address: '544 Newkirk Placez, Bath, Colorado, 8374',
    about:
      'Ex laboris minim ipsum cupidatat irure ullamco ut. Adipisicing irure ullamco ex aliqua consequat nisi aliquip do Lorem Lorem occaecat do dolor est. Cillum mollit veniam cillum exercitation fugiat mollit amet exercitation culpa proident ad cupidatat veniam. Consequat nostrud cupidatat irure ad et minim ea. Qui amet occaecat aute ullamco occaecat aute sunt anim laborum id deserunt proident pariatur. Ad eu occaecat minim officia voluptate occaecat nostrud minim. Tempor do Lorem duis incididunt tempor minim sunt.\r\n',
    registered: '2015-12-08T03:45:22 -09:00',
    latitude: 31.506246,
    longitude: 57.844783,
    tags: ['anim', 'sunt', 'labore', 'eu', 'ad', 'veniam', 'anim'],
    friends: [
      {
        id: 0,
        name: 'Nguyen Porter',
      },
      {
        id: 1,
        name: 'Ray Greene',
      },
      {
        id: 2,
        name: 'English Odom',
      },
    ],
    greeting: 'Hello, Maryellen Foley! You have 5 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '63d36c1c68c42c60200816ed',
    index: 5,
    guid: '6925979f-579a-4ec9-a9e2-ae2fd946f4e9',
    isActive: false,
    balance: '$2,230.70',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'green',
    name: 'Candy Morris',
    gender: 'female',
    company: 'ATGEN',
    email: 'candymorris@atgen.com',
    phone: '+1 (801) 541-3148',
    address: '979 Beverley Road, Camino, Mississippi, 9190',
    about:
      'Culpa Lorem velit aliquip veniam labore dolor fugiat exercitation minim dolor nostrud adipisicing. Sit consequat ex esse ut et proident id ut officia dolor. Non non proident voluptate laboris ut id laborum occaecat nisi commodo. Cupidatat id ea cupidatat laborum. Velit esse sint consequat veniam non qui ad esse duis dolor proident ea id. Reprehenderit id duis sint in nisi nisi duis incididunt ea occaecat eiusmod. Id commodo cillum minim proident occaecat deserunt proident.\r\n',
    registered: '2016-12-17T08:52:34 -09:00',
    latitude: -72.694914,
    longitude: 178.094504,
    tags: ['ut', 'voluptate', 'mollit', 'dolor', 'aute', 'excepteur', 'dolor'],
    friends: [
      {
        id: 0,
        name: 'Dickson Wilson',
      },
      {
        id: 1,
        name: 'Coffey Mcpherson',
      },
      {
        id: 2,
        name: 'Maggie Sawyer',
      },
    ],
    greeting: 'Hello, Candy Morris! You have 10 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '63d36c1c70f93ba0ea9a8a34',
    index: 6,
    guid: 'afbc06ca-c614-4492-bda2-62f1e9f64a94',
    isActive: true,
    balance: '$2,587.00',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'brown',
    name: 'Daniel Hardy',
    gender: 'male',
    company: 'METROZ',
    email: 'danielhardy@metroz.com',
    phone: '+1 (981) 406-3890',
    address: '669 Maujer Street, Nipinnawasee, New Hampshire, 1293',
    about:
      'Ex velit deserunt et pariatur do. Officia est consequat incididunt fugiat ipsum reprehenderit exercitation pariatur deserunt exercitation eu nulla. Et sit occaecat sit deserunt et magna amet aliquip nostrud ipsum do.\r\n',
    registered: '2015-05-27T06:12:25 -09:00',
    latitude: 16.949984,
    longitude: -52.809654,
    tags: ['mollit', 'pariatur', 'qui', 'dolore', 'dolore', 'ipsum', 'veniam'],
    friends: [
      {
        id: 0,
        name: 'Gentry Tyler',
      },
      {
        id: 1,
        name: 'Cathleen Hogan',
      },
      {
        id: 2,
        name: 'Glenda Cantu',
      },
    ],
    greeting: 'Hello, Daniel Hardy! You have 4 unread messages.',
    favoriteFruit: 'apple',
  },
];
